name: CI -> Deploy to Staking
on:
  push:
    branches: master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Here is the deployment action
      - name: Upload from public_html via FTP
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: ${{ secrets.FTP_STAKING_SERVER }}
          user: ${{ secrets.FTP_STAKING_USERNAME }}
          password: ${{ secrets.FTP_STAKING_PASSWORD }}
          local_dir: "./dist"
          remote_dir: "/"
          delete: "false"
      # Here
